table 'Session Lap Telemetry'
	lineageTag: 04e2a44b-431e-408f-86ee-c2bfdbfc0267

	measure Line =
			"LINESTRING ("
			    & CALCULATE(
			        CONCATENATEX('Session Lap Telemetry', 'Session Lap Telemetry'[Coordinate Pair], ",", 'Session Lap Telemetry'[EndTime], ASC )
			    ) & ")"
		lineageTag: f8b43922-587d-436d-875e-da13f234ad12

	column sessionLapKey
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 9347bba5-88cc-4486-80e9-2cad26ce0540
		summarizeBy: none
		sourceColumn: sessionLapKey

		annotation SummarizationSetBy = Automatic

	column EndTime
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 0ffd274f-4f62-4daf-a64f-66d29f73b910
		summarizeBy: none
		sourceColumn: EndTime

		annotation SummarizationSetBy = Automatic

	column Accel
		dataType: double
		sourceProviderType: double
		lineageTag: 9410d1ac-3cf2-42f6-a9f5-9fc2d0b4a2fb
		summarizeBy: sum
		sourceColumn: Accel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Brake
		dataType: double
		sourceProviderType: double
		lineageTag: 10a6f4c1-756e-4e5b-a196-8f0a58e45347
		summarizeBy: sum
		sourceColumn: Brake

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DistanceTraveled
		dataType: double
		sourceProviderType: double
		lineageTag: a67bee31-c5e0-4e91-8a3e-32b0a53fb82b
		summarizeBy: sum
		sourceColumn: DistanceTraveled

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gear
		dataType: double
		sourceProviderType: double
		lineageTag: 32239f37-2f5b-4a28-99d4-497707e7fd4b
		summarizeBy: sum
		sourceColumn: Gear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PositionX
		dataType: double
		sourceProviderType: double
		lineageTag: a24c37ae-ea37-41d6-a1a0-4a599564d0f5
		summarizeBy: sum
		sourceColumn: PositionX

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PositionZ
		dataType: double
		sourceProviderType: double
		lineageTag: f77356cb-5daa-4ae1-8fa7-c96fc7dddea3
		summarizeBy: sum
		sourceColumn: PositionZ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Speed
		dataType: double
		sourceProviderType: double
		lineageTag: e7cc4856-5414-4b0e-8ec0-fd1d6a127007
		summarizeBy: sum
		sourceColumn: Speed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Steer
		dataType: double
		sourceProviderType: double
		lineageTag: 42d822fe-3665-456a-91ec-73a4daddcbf7
		summarizeBy: sum
		sourceColumn: Steer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coordinate Pair' = ROUND('Session Lap Telemetry'[PositionX],2) & " " & ROUND('Session Lap Telemetry'[PositionZ],2)
		lineageTag: 83cf1dfc-1565-41ca-8301-6362332c3f21
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Session Lap Telemetry' = m
		mode: directQuery
		source =
				let
				    Source = AzureDataExplorer.Contents(EventhouseQueryUri, null, null, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    KQLDB = Source{[Name=KQLDB]}[Data],
				    fGetPivotedTelemetryData = KQLDB{[Name="GetPivotedTelemetryData"]}[Data],
				    GetPivotedTelemetryData = fGetPivotedTelemetryData(null)
				in
				    GetPivotedTelemetryData

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

