table 'Session Lap Telemetry'
	lineageTag: 04e2a44b-431e-408f-86ee-c2bfdbfc0267

	measure Line =
			"LINESTRING ("
			    & CALCULATE(
			        CONCATENATEX('Session Lap Telemetry', 'Session Lap Telemetry'[Coordinate Pair], ",", 'Session Lap Telemetry'[Timestamp], ASC )
			    ) & ")"
		lineageTag: f8b43922-587d-436d-875e-da13f234ad12

	column sessionLapKey
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 9347bba5-88cc-4486-80e9-2cad26ce0540
		summarizeBy: none
		sourceColumn: sessionLapKey

		annotation SummarizationSetBy = Automatic

	column 'Coordinate Pair' = ROUND('Session Lap Telemetry'[PositionX],2) & " " & ROUND('Session Lap Telemetry'[PositionZ],2)
		lineageTag: 83cf1dfc-1565-41ca-8301-6362332c3f21
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column LapId
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 641f110f-2e86-43a4-a2c5-65bcd5402b59
		summarizeBy: none
		sourceColumn: LapId

		annotation SummarizationSetBy = Automatic

	column CarId
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 4ac23132-76dc-4603-a3e0-45be90de3d40
		summarizeBy: none
		sourceColumn: CarId

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 574622ec-cd34-4377-b3f9-120d4b761429
		summarizeBy: none
		sourceColumn: Timestamp

		annotation SummarizationSetBy = Automatic

	column Accel
		dataType: double
		sourceProviderType: double
		lineageTag: b1dc6759-e40b-4123-bd3a-7b2f14285a9b
		summarizeBy: sum
		sourceColumn: Accel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Break
		dataType: double
		sourceProviderType: double
		lineageTag: 9992f0a8-964c-4185-a327-c00b64ab25eb
		summarizeBy: sum
		sourceColumn: Break

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DistanceTraveled
		dataType: double
		sourceProviderType: double
		lineageTag: 08d074a3-d6ce-4b20-bf27-0d40bb5a9ee2
		summarizeBy: sum
		sourceColumn: DistanceTraveled

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gear
		dataType: double
		sourceProviderType: double
		lineageTag: b7145aeb-c507-4b37-b94d-b5e9c266605a
		summarizeBy: sum
		sourceColumn: Gear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PositionX
		dataType: double
		sourceProviderType: double
		lineageTag: 6d9b607b-2843-4d78-aa26-4232ff910347
		summarizeBy: sum
		sourceColumn: PositionX

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PositionZ
		dataType: double
		sourceProviderType: double
		lineageTag: dad29d74-f9d9-4c34-99f6-ea0b02c4097a
		summarizeBy: sum
		sourceColumn: PositionZ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Speed
		dataType: double
		sourceProviderType: double
		lineageTag: b081554c-74a3-4ad9-a61a-a0e6ec1d2087
		summarizeBy: sum
		sourceColumn: Speed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Steer
		dataType: double
		sourceProviderType: double
		lineageTag: 953294a8-cf75-4b66-bfe2-83fec08f98e5
		summarizeBy: sum
		sourceColumn: Steer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Session Lap Telemetry' = m
		mode: directQuery
		source =
				let
				    Source = KustoConnection,
				    fGetPivotedTelemetryData = Source{[Name="GetPivotedTelemetryData"]}[Data],
				    GetPivotedTelemetryData = fGetPivotedTelemetryData(SelectedDate),
				    #"Renamed Columns" = Table.RenameColumns(GetPivotedTelemetryData,{{"Accel", "Accel"}, {"Brake", "Break"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

